name: Linting

on:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y clang-format-21
      - name: Run clang-format
        run: |
          result=0
          for file in $(git ls-files '*.cpp' '*.hpp'); do
            if ! clang-format-21 --dry-run --Werror "$file"; then
              result=1
            fi
          done
          exit $result

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt clang-tidy
      - name: Create dummy.cpp file
        run: echo -e '#include "ecs/ecs.hpp" > dummy.cpp
      - name: Run clang-tidy
        run: clang-tidy dummy.cpp --header-filter=".*" -- -std=c++20

  include-what-you-use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install iwyu
      - name: Run include-what-you-use
        run: |
          result=0
          for file in $(git ls-files 'ecs/*.hpp'); do
            if ! include-what-you-use -std=c++20 "$file"; then
              result=1
            fi
          done
          exit $result
