name: Linting

on:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y clang-format-21
      - name: Run clang-format
        run: |
          result=0
          for file in $(git ls-files '*.cpp' '*.hpp'); do
            if ! clang-format-21 --dry-run --Werror "$file"; then
              result=1
            fi
          done
          exit $result

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev ninja-build clang-tidy
      - name: CMake Configure
        run: cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTINYECS_THIRD_PARTY_BENCHMARKS=ON
      - name: Run clang-tidy
        run: git ls-files -z '*.cpp' | xargs -r -0 clang-tidy -p build

  include-what-you-use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev ninja-build iwyu
      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DTINYECS_USE_IWYU=On -DTINYECS_THIRD_PARTY_BENCHMARKS=ON
          cmake --build build --parallel $(nproc)
